### ISSUE TITLE
limit alert shows up but not disappear.

### ISSUE THREAD

**Issue by minju25kim** [lascellesabercrombie/SquareGame#3]
I created the alert for the users to not to go further than the board size.

- 'you can't go further'

The alert shows up as span but not disappear after the player's coordinates has changed in the board.

**Comment by lascellesabercrombie** [comment]
I have added an else case for xLimitAlert and yLimitAlert so that if the player is not at the edge of the board, the alert's textContent is null. There might be a neater way of doing this but it seems to be working for now!
